### ISSUE TITLE
.env file not working

### ISSUE THREAD

**Issue by robgarrett** [elliotmatson/Docker-Davinci-Resolve-Project-Server#111]
I've created the following content in a .env file, which is at the same location as the docker-compose.yml file. 

PGADMIN_DEFAULT_EMAIL=my@email.com
PGADMIN_DEFAULT_PASSWORD=DaVinci
POSTGRES_LOCATION=/root/.davinci/db:/var/lib/postgresql/data
BACKUP_LOCATION=/root/.davinci/backups:/backups
TZ=America/New_York

I'd like to just clone this repo and not have to edit the compose file.

**Comment by elliotmatson** [comment]
Yea, that's the way I would prefer to do things as well. 

The reason I chose to do it the current way is that some platforms (QNAP if I recall correctly) don't let you use .env files, so that would break this project for those users. I'm not sure there's a great way to get around that limitation unfortunately
